<?php
  $base_grant_url = urldecode($_GET['base_grant_url']);
  $user_continue_url = urldecode($_GET['user_continue_url']);
  $override_continue_url = 'http://luckybrand.com';
  
  $override_the_users_request = false;
  if ($override_the_users_request) {
    $grant_url = $base_grant_url . "?continue_url=" . urlencode($override_continue_url);
  } else {
    $grant_url = $base_grant_url . "?continue_url=" . urlencode($user_continue_url);
  }

  // The following parameters may be used for tracking purposes. They are not necessary for authentication.
  $node_id = urldecode($_GET['node_id']);
  $node_mac = urldecode($_GET['node_mac']);
  $gateway_id = urldecode($_GET['gateway_id']);
  $client_ip = urldecode($_GET['client_ip']);
  $client_mac = urldecode($_GET['client_mac']);

?>
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the faviconFolder directory -->
        <link rel="apple-touch-icon" sizes="152x152" href="faviconFolder/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="faviconFolder/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="faviconFolder/favicon-16x16.png">
        <link rel="manifest" href="faviconFolder/manifest.json">
        <link rel="mask-icon" href="faviconFolder/safari-pinned-tab.svg" color="#5bbad5">
        <meta name="theme-color" content="#ffffff">



        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <link rel="stylesheet" href="css/spot_fb_button.css">
        <script src="js/vendor/modernizr-2.8.3.min.js"></script>
        <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- FACEBOOK LOGIN SCRIPT -->
        <div id="fb-root"></div>
        <script type="text/javascript" src="js/facebook.js"></script>

        <!-- Add your site or application content here -->
        <div class="Wrapper">
            <picture class="bgPic">
                <source media="(min-width: 631px)" srcset="img/SplashPage_Bg.png">
                <source media="(max-width: 630px)" srcset="img/Mob_SplashPage_Bg.png">
                <img src="img/SplashPage_Bg" alt="Lucky Brand Public Wi-Fi Splash Page Image">
            </picture>
            <div class="EmailForm">
                <div class="LogoWrapper">
                    <img src="img/SplashPage_Logo_03.png" alt="Lucky Brand Logo">
                </div>
                <!-- <p class="TopRow">Home is Where the Wi-Fi Automatically Connects</p> -->
                <p class="MiddleRow">Free Wi-Fi</p>
                <p class="BottomRow">With email sign-up</p>
                <br>
                <!-- <form action="http://bm5150.com/public/webform/process/" method="post"> -->
                    <input type="hidden" name="fid" value="ahwtnn08oquhocfjsqa0xacaqsypt" />
                    <input type="hidden" name="sid" value="62170228a0d96469816719af91803b7a" />
                    <input type="hidden" name="delid" value="" />
                    <input type="hidden" name="subid" value="" />
                    <input type="hidden" name="td" value="" />
                    <input type="hidden" name="formtype" value="addcontact" />
                    <script type="text/javascript">
                        var fieldMaps = {};
                    </script>

                        <div class="form-group email-group" id="column_14334">
                            <div class="placeholder">
                                <label for="email">Email Address</label>
                                <span class="star">*</span>
                            </div>
                            <input type="text" class="form-control" size="35" name="32411" value=""  id="required" />
                        </div>

                        <!-- <div class="container" id="column_14335">
                            <div class="field_block" field_id="76517" >
                                <div id="caption_76517" class="caption">Gender</div>
                                <div class="radio field">
                                    <span>
                                        <input type="radio" id="fieldoption_52682" class="radio field" name="32414" value="male" />
                                        <label class="fieldoptiongender" for="fieldoption_52682">Male</label>
                                    </span>
                                    <span>
                                        <input type="radio" id="fieldoption_52683" class="radio field" name="32414" value="female" />
                                        <label class="fieldoptiongender" for="fieldoption_52683">Female</label>
                                    </span>
                                    <div class="field_error"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="legalVerbal">
                    	Welcome to Lucky Brand’s free Wi-Fi Service.  Please provide the requested information to use the Wi-Fi Service.  In addition to the requested information, you agree that Lucky Brand may collect other information about you, such as information about your wireless device (e.g., device type, MAC Address, IP Address), the location of the store in which you are accessing Lucky Brand's free Wi-Fi Service, and the websites you visit to better understand your experience with Lucky Brand and to improve our services and advertising.  You consent to this collection, and you further  agree that we can use your information as provided in our Privacy Policy at the link below.
                    </div> -->
                    <div class="terms-div">
                        <input type="radio" id="fieldoption_52684" class="radioField" name="32415" value="agree" />
                        <div class="terms-label">I AGREE TO THE <u><a href="http://www.luckybrand.com/terms-of-use/terms-of-use.html">TERMS OF SERVICES</a></u> AND HAVE REVIEWED THE <u><a href="PrivacyPage.html">LUCKY BRAND PRIVACY POLICY</a></u></div>
                    </div>
                    <br>
                    <div class="section" id="row_11572">
                        <div class="container" id="column_14336">
                            <div class="field_block">
                                <div class="field">
                                    <span>
                                        <input class="connect" id="connect_btn" type="submit" value="CONNECT NOW"/>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="button_container">
                        <!-- Spotify Button -->
                        <button class="btn btn-primary" id="btn-login">Log in With Spotify</button>

                        <!-- Facebook Button -->
                        <div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false" scope="public_profile,email" onlogin="checkLoginState();"></div>
                    </div>

                <!-- </form> -->
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.12.0.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
     <!--    <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script> -->
 		<!-- Google Analytics. -->
        <script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-103139859-1', 'auto');
			ga('send', 'pageview');
		</script>
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script type="text/javascript">
            // Internet Explorer 6-11
            var isIE = /*@cc_on!@*/false || !!document.documentMode;
            // Chrome 1+
            var isChrome = !!window.chrome && !!window.chrome.webstore;
            // Safari 3.0+ "[object HTMLElementConstructor]" 

            $(document).ready(function(){
                $(".fieldRetry").hide();
                $(".fieldYes").hide();
                $(".fieldNo").hide();
                $(".sk-circle").hide();
                $(".bgPic").hide();

                // Determines which browser it is on
                if(isIE) {
                    document.getElementsByTagName("BODY")[0].setAttribute("background","img/SplashPage_Bg.png");
                    $(".ScanForm").css('margin-top', '230px');
                } else {
                    $(".bgPic").show();
                }
            });

            var client_ip = <?php echo json_encode($client_ip); ?>;
            var client_mac = <?php echo json_encode($client_mac); ?>;
            var node_id = <?php echo json_encode($node_id); ?>;
            var node_mac = <?php echo json_encode($node_mac); ?>;
            var gateway_id = <?php echo json_encode($gateway_id); ?>;

            var grantUrl=<?php echo json_encode($grant_url); ?>;
            document.cookie = "username="+grantUrl; // idk why i called it username 

            document.cookie = "client_ip="+client_ip;
            document.cookie = "client_mac="+client_mac;
            document.cookie = "node_id="+node_id;
            document.cookie = "node_mac="+node_mac;
            document.cookie = "gateway_id="+gateway_id;



            /***********
            Making placeholder star specifically red 
            ****************/

            $('.placeholder').click(function() {
              $(this).siblings('input').focus();
            });
            $('.form-control').focus(function() {
              $(this).siblings('.placeholder').hide();
            });
            $('.form-control').blur(function() {
              var $this = $(this);
              if ($this.val().length == 0)
                $(this).siblings('.placeholder').show();
            });
            $('.form-control').blur();

        </script>

        <!-- Email Login Script -->
        <script type="text/javascript" src="js/email.js"></script>

        <!-- Spotify Login Script -->
        <script type="text/javascript" src="js/spotify.js"></script>

    </body>
</html>
